services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: helloworld
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: hello
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
